apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reklame
  namespace: production
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
  - hosts:
    - reklame.prpo.timhrovat.com
    secretName: reklame-tls
  rules:
  - host: reklame.prpo.timhrovat.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: reklame
            port:
              number: 8080
