services:
  nakup:
    ports:
      - "8082:8082"
    restart: always
    build: .
    environment:
      - LOG_LEVEL=DEBUG
      - TZ=
      - SPORED_HOST=localhost:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/healthcheck"]
      interval: 3s
      timeout: 10s
      retries: 5