services:
  reklame:
    ports:
      - "8083:8080"
    restart: always
    build: .
    environment:
      - LOG_LEVEL=DEBUG
      - TZ=
      - SPORED_HOST=localhost:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthcheck"]
      interval: 3s
      timeout: 10s
      retries: 5